### ISSUE TITLE
Setting parameters of CollisionFreeSpeedModelV2

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/jupedsim#1413] opened 2024-05-08 17:06 UTC
I'm trying to change `strength_neighbor_repulsion` of the agents
like so 

```
simulation = jps.Simulation(
        model=jps.CollisionFreeSpeedModelV2(),
        geometry=geometry,
        dt=_time_step,
        trajectory_writer=jps.SqliteTrajectoryWriter(
            output_file=pathlib.Path(_trajectory_path), every_nth_frame=_fps
        ),
    )  

for agent_id in ped_ids:
        simulation.agent(agent_id).model.v0 = 2.0
        simulation.agent(agent_id).model.strength_neighbor_repulsion = 2.0
        print(simulation.agent(agent_id).model.v0,
              simulation.agent(agent_id).model.strength_neighbor_repulsion)
```

However, it seems I don't get it right and get as a result:

```
2.0 and 0.5 instead or 2.0 and 2.0
```

Edit: While `v0` gets updated `strength_neighbor_repulsion` does not.

Any idea what I'm doing wrong?

**Comment by Ozaq** [comment] 2024-05-10 05:35
Your code looks fine on first glance, I’ll have a look at it.

**Comment by Ozaq** [comment] 2024-05-11 10:00
@chraibi I need an runnable example that exhibits this behaviour. I created a test for this case and cannot reproduce the bug.

This test passes and this test should do the same as you have provided in your example
https://github.com/PedestrianDynamics/jupedsim/blob/1732ea43c99a365b3cf9c0c27f9702869f1b59ac/systemtest/test_model_properties.py#L50

**Comment by Ozaq** [comment] 2024-05-13 08:54
Yeah I found that issue for `strength_neighbor_repulsion` too when creating the test, this is already fixed on https://github.com/PedestrianDynamics/jupedsim/tree/1413-setting-parameters-of-collisionfreespeedmodelv2

In your original issue you mentioned that `v0` would not update, could you reproduce this? 

I plan on extending the test coverage for all models on this branch and the merging the fix.

**Comment by chraibi** [comment] 2024-05-13 09:45
Nice! Your fix works!

<img width="1412" alt="Screenshot 2024-05-13 at 11 44 39" src="https://github.com/PedestrianDynamics/jupedsim/assets/5772973/f008e9a5-50e7-4d95-8933-084a415a207e">

**Closed** 2024-05-20 07:34 UTC
Labels: Bug
